{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0",
    "title": "Favorite Products API",
    "description": "This project is based on the management of each customer's favorite products for generating marketing reports."
  },
  "servers":[
    { "url" : "http://localhost:3000"}
  ],
  "tags": [
    { "name": "Session", "description": "Features to handle the session." },
    { "name": "Client", "description": "Features to handle the client data." },
    { "name": "Product", "description": "Features to handle the client data." }
  ],
  "schemes": ["http"],
  "paths": {
    "/api/v1/session/token": {
      "post": {
        "tags": ["Session"],
        "summary": "Obtain a JWT token by validating an access code.",
        "description": "The JWT token expires in one hour after your creation.",
        "requestBody":{
          "description": "The default access code is _'fpPrjAccessCode'_, but can be changed by the **ACCESS_CODE** environment variable.",
          "required": true,
          "content":{
            "application/json":{
              "schema":{
                "type":"object",
                "properties":{
                  "accessCode":{
                    "type":"string"
                  }
                }
              },
              "example":{
                "accessCode": "fpPrjAccessCode"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation.",
            "content":{
              "application/json":{
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": { "type": "string" }
                  }
                },
                "example":{
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
                }
              }
            }
          },
          "400": {
            "description": "Invalid body request.",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                },
                "example":{
                  "message": "Invalid body request."
                }
              }
            }
          },
          "401": {
            "description": "Access code does not valid.",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                },
                "example":{
                  "message": "Access code does not valid."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error.",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                },
                "example":{
                  "message": "Internal server error."
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/client": {
      "get": {
        "security": [
          {"JWTAuth": []}
        ],
        "tags": ["Client"],
        "summary": "Get all client records.",
        "parameters":[
          {
            "in":"query",
            "name":"page",
            "schema":{
              "type": "integer"
            },
            "description":"Defines the page number among the pagination you want to obtain. If not defined, it will be assumed as page 1."
          }
        ],
        "produces": ["application/json"],
        "responses": {
          "200": {
            "description": "Successful operation.",
            "content":{
              "application/json":{
                "schema": {
                  "type": "object",
                  "properties":{
                    "docs":{
                      "type": "array",
                      "items": {
                        "type": "object",
                        "$ref": "#/components/schemas/Client"
                      }
                    },
                    "total": { "type":"number" },
                    "limit": { "type":"number" },
                    "page": { "type":"number" },
                    "pages": { "type":"number" }
                  }
                },
                "example": {
                  "docs": [{
                    "_id": "a1b2c3",
                    "name": "José",
                    "email": "jose@fp.com",
                    "favorite_products": ["c3b2a1"],
                    "createdAt": "2020-09-19T21:04:04.130Z",
                    "updatedAt": "2020-09-19T21:04:04.130Z"
                  }],
                  "total": 1,
                  "limit": 10,
                  "page": 1,
                  "pages": 1
                }
              }
            }
          },
          "401": {
            "description": "'JWT token is missing.' or 'Invalid JWT token.'",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error.",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                },
                "example":{
                  "message": "Internal server error."
                }
              }
            }
          }
        }
      },
      "post":{
        "security": [
          {"JWTAuth": []}
        ],
        "tags": ["Client"],
        "summary": "Create a new client record.",
        "requestBody":{
          "required": true,
          "content":{
            "application/json":{
              "schema":{
                "type": "object",
                "$ref": "#/components/schemas/Client"
              },
              "example":{
                "name": "José",
                "email": "jose@fp.com",
                "favorite_products": []
              }
            }
          }
        },
        "produces": ["application/json"],
        "responses": {
          "200": {
            "description": "Successful operation.",
            "content":{
              "application/json":{
                "schema": {
                  "type": "object",
                  "properties":{
                    "message":{
                      "id":"string"
                    }
                  }
                },
                "example":{
                  "id": "a1b2c3"
                }
              }
            }
          },
          "400": {
            "description": "'Client already exist.' or 'Invalid body request.'",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "'JWT token is missing.' or 'Invalid JWT token.'",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Unknown product among favorites.",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                },
                "example":{
                  "message": "Unknown product among favorites."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error.",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                },
                "example":{
                  "message": "Internal server error."
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/client/{clientCode}": {
      "get":{
        "security": [
          {"JWTAuth": []}
        ],
        "tags": ["Client"],
        "summary": "Get a specific client record.",
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "clientCode",
            "in": "path",
            "description": "Client identification code.",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation.",
            "content":{
              "application/json":{
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Client"
                },
                "example": {
                  "_id": "a1b2c3",
                  "name": "José",
                  "email": "jose@fp.com",
                  "favorite_products": ["c3b2a1"],
                  "createdAt": "2020-09-19T21:04:04.130Z",
                  "updatedAt": "2020-09-19T21:04:04.130Z"
                }
              }
            }
          },
          "401": {
            "description": "'JWT token is missing.' or 'Invalid JWT token.'",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Client not found.",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                },
                "example":{
                  "message": "Client not found."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error.",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                },
                "example":{
                  "message": "Internal server error."
                }
              }
            }
          }
        }
      },
      "put":{
        "security": [
          {"JWTAuth": []}
        ],
        "tags": ["Client"],
        "summary": "Update data of a specific client record.",
        "produces": ["application/json"],
        "requestBody":{
          "required": true,
          "content":{
            "application/json":{
              "schema":{
                "type": "object",
                "$ref": "#/components/schemas/Client"
              },
              "example":{
                "name": "José",
                "email": "jose@fp.com",
                "favorite_products": []
              }
            }
          }
        },
        "parameters": [
          {
            "name": "clientCode",
            "in": "path",
            "description": "Client identification code.",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation.",
            "content":{
              "application/json":{
                "schema":{
                  "type": "object",
                  "$ref": "#/components/schemas/Client"
                },
                "example":{
                  "_id": "a1b2c3",
                  "name": "José",
                  "email": "jose@fp.com",
                  "favorite_products": [],
                  "createdAt": "2020-09-19T21:04:04.130Z",
                  "updatedAt": "2020-09-19T21:04:04.130Z"
                }
              }
            }
          },
          "400": {
            "description": "'The updated client already exists.' or 'Invalid body request.'",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "'JWT token is missing.' or 'Invalid JWT token.'",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "'Client not found.' or 'Unknown product among favorites.'",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error.",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                },
                "example":{
                  "message": "Internal server error."
                }
              }
            }
          }
        }
      },
      "delete":{
        "security": [
          {"JWTAuth": []}
        ],
        "tags": ["Client"],
        "summary": "Delete a specific client record.",
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "clientCode",
            "in": "path",
            "description": "Client identification code.",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation."
          },
          "401": {
            "description": "'JWT token is missing.' or 'Invalid JWT token.'",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Client not found.",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                },
                "example":{
                  "message": "Client not found."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error.",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                },
                "example":{
                  "message": "Internal server error."
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/product": {
      "get": {
        "security": [
          {"JWTAuth": []}
        ],
        "tags": ["Product"],
        "summary": "Get all product records.",
        "parameters":[
          {
            "in":"query",
            "name":"page",
            "schema":{
              "type": "integer"
            },
            "description":"Defines the page number among the pagination you want to obtain. If not defined, it will be assumed as page 1."
          }
        ],
        "produces": ["application/json"],
        "responses": {
          "200": {
            "description": "Successful operation.",
            "content":{
              "application/json":{
                "schema": {
                  "type": "object",
                  "properties":{
                    "docs":{
                      "type": "array",
                      "items": {
                        "type": "object",
                        "$ref": "#/components/schemas/Product"
                      }
                    },
                    "total": { "type":"number" },
                    "limit": { "type":"number" },
                    "page": { "type":"number" },
                    "pages": { "type":"number" }
                  }
                },
                "example": {
                  "docs": [{
                    "_id": "a1b2c3",
                    "title": "Product-X",
                    "brand": "X-Company",
                    "image": "https://www.x-images.com/productX.png",
                    "price": 123.45,
                    "review_score": 8.7,
                    "createdAt": "2020-09-19T21:04:04.130Z",
                    "updatedAt": "2020-09-19T21:04:04.130Z"
                  }],
                  "total": 1,
                  "limit": 10,
                  "page": 1,
                  "pages": 1
                }
              }
            }
          },
          "401": {
            "description": "'JWT token is missing.' or 'Invalid JWT token.'",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error.",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                },
                "example":{
                  "message": "Internal server error."
                }
              }
            }
          }
        }
      },
      "post":{
        "security": [
          {"JWTAuth": []}
        ],
        "tags": ["Product"],
        "summary": "Create a new product record.",
        "requestBody":{
          "required": true,
          "content":{
            "application/json":{
              "schema":{
                "type": "object",
                "$ref": "#/components/schemas/Product"
              },
              "example":{
                "title": "Product-X",
                "brand": "X-Company",
                "image": "https://www.x-images.com/productX.png",
                "price": 123.45,
                "review_score": 8.7
              }
            }
          }
        },
        "produces": ["application/json"],
        "responses": {
          "200": {
            "description": "Successful operation.",
            "content":{
              "application/json":{
                "schema": {
                  "type": "object",
                  "properties":{
                    "message":{
                      "id":"string"
                    }
                  }
                },
                "example":{
                  "id": "a1b2c3"
                }
              }
            }
          },
          "400": {
            "description": "'Product already exist.' or 'Invalid body request.'",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "'JWT token is missing.' or 'Invalid JWT token.'",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error.",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                },
                "example":{
                  "message": "Internal server error."
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/product/{productCode}": {
      "get":{
        "security": [
          {"JWTAuth": []}
        ],
        "tags": ["Product"],
        "summary": "Get a specific product record.",
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "productCode",
            "in": "path",
            "description": "Product identification code.",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation.",
            "content":{
              "application/json":{
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Product"
                },
                "example": {
                  "_id": "a1b2c3",
                  "title": "Product-X",
                  "brand": "X-Company",
                  "image": "https://www.x-images.com/productX.png",
                  "price": 123.45,
                  "review_score": 8.7,
                  "createdAt": "2020-09-19T21:04:04.130Z",
                  "updatedAt": "2020-09-19T21:04:04.130Z"
                }
              }
            }
          },
          "401": {
            "description": "'JWT token is missing.' or 'Invalid JWT token.'",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Product not found.",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                },
                "example":{
                  "message": "Product not found."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error.",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                },
                "example":{
                  "message": "Internal server error."
                }
              }
            }
          }
        }
      },
      "put":{
        "security": [
          {"JWTAuth": []}
        ],
        "tags": ["Product"],
        "summary": "Update data of a specific product record.",
        "produces": ["application/json"],
        "requestBody":{
          "required": true,
          "content":{
            "application/json":{
              "schema":{
                "type": "object",
                "$ref": "#/components/schemas/Product"
              },
              "example": {
                "title": "Product-X",
                "brand": "X-Company",
                "image": "https://www.x-images.com/productX.png",
                "price": 123.45,
                "review_score": 8.7
              }
            }
          }
        },
        "parameters": [
          {
            "name": "productCode",
            "in": "path",
            "description": "Product identification code.",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation.",
            "content":{
              "application/json":{
                "schema":{
                  "type": "object",
                  "$ref": "#/components/schemas/Product"
                },
                "example": {
                  "_id": "a1b2c3",
                  "title": "Product-X",
                  "brand": "X-Company",
                  "image": "https://www.x-images.com/productX.png",
                  "price": 123.45,
                  "review_score": 8.7,
                  "createdAt": "2020-09-19T21:04:04.130Z",
                  "updatedAt": "2020-09-19T21:04:04.130Z"
                }
              }
            }
          },
          "400": {
            "description": "'The updated product already exists.' or 'Invalid body request.'",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "'JWT token is missing.' or 'Invalid JWT token.'",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Product not found.",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                },
                "example":{
                  "message": "Product not found."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error.",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                },
                "example":{
                  "message": "Internal server error."
                }
              }
            }
          }
        }
      },
      "delete":{
        "security": [
          {"JWTAuth": []}
        ],
        "tags": ["Product"],
        "summary": "Delete a specific product record.",
        "produces": ["application/json"],
        "parameters": [
          {
            "name": "productCode",
            "in": "path",
            "description": "Product identification code.",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation."
          },
          "401": {
            "description": "'JWT token is missing.' or 'Invalid JWT token.'",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Product not found.",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                },
                "example":{
                  "message": "Product not found."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error.",
            "content":{
              "application/json":{
                "schema": {
                  "type":"object",
                  "properties":{
                    "message":{
                      "type":"string"
                    }
                  }
                },
                "example":{
                  "message": "Internal server error."
                }
              }
            }
          }
        }
      }
    }
  },
  "components":{
    "securitySchemes":{
      "JWTAuth":{
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT" ,
        "description": "Enter **_only_**  the JWT token obtained in the session route."
      }
    },
    "schemas":{
      "Client": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "email": { "type": "string" },
          "favorite_products": {
            "type": "array",
            "items": {
              "type": "object",
              "$ref": "#/components/schemas/Product"
            }
          }
        }
      },
      "Product": {
        "type": "object",
        "properties": {
          "title": { "type": "string" },
          "brand": { "type": "string" },
          "image": { "type": "string" },
          "price": { "type": "number" },
          "review_score": { "type": "number" }
        }
      }
    }
  }
}
